service: lambda-github-check

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-north-1'}
  memorySize: ${opt:memory, 512}
  timeout: 10
  logRetentionInDays: 7
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}
  apiGateway:
    minimumCompressionSize: 1024

package:
  individually: true
  patterns:
    - '!*'
    - '!**/*'
    - 'package.json'
    - 'src/*'
    - 'node_modules/**/*'

functions:
  GitHubAppHandler:
    handler: src/index.handler
    description: GitHub App handler
    events:
      - http:
          method: POST
          path: /
    environment:
      GITHUB_APP_PRIVATE_KEY: ''
      GITHUB_APP_ID: ''
      GITHUB_APP_SECRET: ''